nei <- readRDS("summarySCC_PM25.rds")
scc <- readRDS("Source_Classification_Code.rds")
s = subset(nei, nei$fips=="24510")
t= tapply(s$Emissions, s$year, sum)
y = data.frame(sum = t, year = rownames(t))
plot(as.character(y$year), y$sum, col = y$year, xlab = "year", ylab = "Total PM2.5 emission(in tons)", main = "Total emission in Baltimore City")
lines(as.character(y$year), y$sum)
dev.copy(png, "plot2.png")
dev.off()