nei <- readRDS("summarySCC_PM25.rds")
scc <- readRDS("Source_Classification_Code.rds")
x = data.frame(tapply(nei$Emissions, nei$year, sum), unique(nei$year))
names(x)= c("sum", "year")
x$year = as.character(x$year)
plot(x$year, x$sum, xlab= "year", ylab = "total PM2.5 emission", main = "Total PM2.5 emission(1999-2008)")
lines(x$year, x$sum, col = "blue")
dev.copy(png, "plot1.png")
dev.off()